import Head from 'next/head';
import '../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import 'react-toastify/dist/ReactToastify.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import '../styles/antd.dark.css';

import {
  getDefaultWallets,
  RainbowKitProvider,
  darkTheme,
} from '@rainbow-me/rainbowkit';
import { chain, configureChains, createClient, WagmiConfig } from 'wagmi';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';
import { MoralisProvider } from 'react-moralis';
import { ToastContainer } from 'react-toastify';

const { chains, provider, webSocketProvider } = configureChains(
  [chain.mainnet, chain.polygon, chain.arbitrum, chain.goerli, chain.hardhat],
  [alchemyProvider({ apiKey: process.env.ALCHEMY_API_KEY }), publicProvider()],
);

const { connectors } = getDefaultWallets({
  appName: 'NFT Marketplace - Moralis',
  chains,
});

const wagmiClient = createClient({
  provider,
  webSocketProvider,
  autoConnect: true,
  connectors,
});

function MyApp({ Component, pageProps }) {
  return (
    <div id='container'>
      <Head>
        <title>NFT Marketplace - Moralis</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <WagmiConfig client={wagmiClient}>
        <RainbowKitProvider
          chains={chains}
          modalSize={{
            smallScreen: 'compact',
            largeScreen: 'wide',
          }}
          theme={darkTheme({
            accentColor: 'rgb(var(--alt-color))',
            accentColorForeground: '#fff',
            borderRadius: 'small',
            fontStack: 'rounded',
            overlayBlur: 'small',
          })}
        >
          <MoralisProvider
            appId={process.env.NEXT_PUBLIC_MORALIS_APP_ID}
            serverUrl={process.env.NEXT_PUBLIC_MORALIS_APP_URL}
          >
            <Component {...pageProps} />
          </MoralisProvider>
        </RainbowKitProvider>
      </WagmiConfig>
      <ToastContainer theme='colored' progressStyle={{ background: '#fff' }} />
    </div>
  );
}

export default MyApp;
